IP_ADDRESS = "10.0.10.20"
PROXMOX_PORT = 8006

Vagrant.configure(2) do |config|
  config.vm.box = "phaus/proxmox"
  config.vm.hostname = "proxmox"

  config.vm.provider "virtualbox" do |box|
    box.name = "proxmox"
    box.memory = 1024 * 12
  end

  config.vm.network "forwarded_port", guest: PROXMOX_PORT, host: PROXMOX_PORT
  config.vm.network "private_network", ip: IP_ADDRESS
end
