NODE_COUNT = Integer(ENV['NODE_COUNT'] || "1")
IP_PREFIX = "10.0.10"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/impish64"

  (1..NODE_COUNT).each do |index|
    config.vm.hostname = "MAAS node #{index}"
    config.vm.provider "virtualbox" do |box|
      box.name = "MAAS-node-#{index}"
      box.memory = 1028
    end

    config.vm.network "private_network", ip: "#{IP_PREFIX}.#{(index+20).to_s.rjust(2, '0')}"
  end

end
