#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 26 13:37:45 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=photon_v1.3b.zip
enableShaders=true
